DECLARE @vehId int
SELECT @vehId = 1000
WHILE @vehId < 5000
BEGIN
	INSERT INTO CONVMSVEHICLETABLE
	    (VEHICLEID, VEHICLEGROUPID, [NAME], DATAAREAID)
	    VALUES ('V'+cast(@vehId AS nvarchar), '1', 'Test name', 'ZZZ')

	DECLARE @servId int
	SELECT @servId = 1
	WHILE @servId < 50
	BEGIN
		INSERT INTO CONVMSVEHICLESERVICETABLE
			(VEHICLEID, SERVICEID, SERVICESTATUS, SERVICEDATEREQ, DATAAREAID)
			VALUES ('V'+cast(@vehId AS nvarchar), 'S'+cast(@vehId * @servId as nvarchar), 2, GETUTCDATE(), 'ZZZ')
		SELECT @servId = @servId + 1
	END
	SELECT @vehId = @vehId + 1
END

INSERT into CONVMSVEHICLEGROUP (VEHICLEGROUPID, [NAME], DATAAREAID) VALUES ('1', 'Veh Group name', 'ZZZ')

delete from CONVMSVEHICLETABLE WHERE DATAAREAID = 'ZZZ'
delete from CONVMSVEHICLESERVICETABLE  WHERE DATAAREAID = 'ZZZ'
delete from CONVMSVEHICLEGROUP   WHERE DATAAREAID = 'ZZZ'
